version: "3.8"

services:
  cooking-center-db:
    container_name: cooking-center-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pg
      POSTGRES_USER: pg
      POSTGRES_DB: cc
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./data/:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


